version: '3.8'
services:
  api:
    build: ./
    depends_on:
      - redis
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: CompileDaemon -build='go build -o /usr/local/bin/app' -command='/usr/local/bin/app'

  redis:
    image: redis
    ports:
      - 6379
    volumes: 
      - .:/app